version: '3.3'
services:
  tomcat:
    build:
      context: .
    image: tomcat:9
    ports:
      - "8080:8080"
    volumes:
      - ./target/com.ut.mizdooni.war:/usr/local/tomcat/webapps/com.ut.mizdooni.war
